#!/usr/bin/env bash
# Bootstrap/reconcile the XTRM security baseline on one repository.
# Review the generated diff and repository policy before merging.
set -euo pipefail

if [ $# -ne 1 ]; then
  echo "Usage: $0 <target-repo-path>" >&2
  exit 1
fi

TARGET="$(cd "$1" && pwd)"
SOURCE="$(cd "$(dirname "$0")/.." && pwd)"

if [ ! -d "$TARGET/.git" ]; then
  echo "error: $TARGET is not a git repository" >&2
  exit 1
fi

cd "$TARGET"
command -v gh >/dev/null || { echo "error: gh is required" >&2; exit 1; }
gh auth status >/dev/null 2>&1 || { echo "error: gh is not authenticated" >&2; exit 1; }

SLUG="$(gh repo view --json nameWithOwner --jq .nameWithOwner)"
DEFAULT_BRANCH="$(gh repo view --json defaultBranchRef --jq '.defaultBranchRef.name // "main"')"
BRANCH="feat/security-bootstrap-$(date +%Y%m%d)"

echo "Target: $SLUG (default branch: $DEFAULT_BRANCH)"

# Detect dependency ecosystems. Keep one block per root ecosystem; monorepos
# must be reviewed manually after generation.
ECOSYSTEMS=()
HAS_PIP=0
if [ -f requirements.txt ] || find . -maxdepth 3 -name 'requirements*.txt' -not -path '*/node_modules/*' -print -quit | grep -q .; then
  HAS_PIP=1
fi
[ -f pyproject.toml ] && HAS_PIP=1
[ "$HAS_PIP" = 1 ] && ECOSYSTEMS+=(pip)
[ -f package.json ] && ECOSYSTEMS+=(npm)
find . -maxdepth 5 -name Dockerfile -not -path '*/node_modules/*' -print -quit | grep -q . && ECOSYSTEMS+=(docker)
[ -f go.mod ] && ECOSYSTEMS+=(gomod)
[ -f Cargo.toml ] && ECOSYSTEMS+=(cargo)
ECOSYSTEMS+=(github-actions)

git fetch origin --quiet
git checkout -b "$BRANCH" 2>/dev/null || git checkout "$BRANCH"

copy_file() {
  local rel="$1"
  local src="$SOURCE/templates/$rel"
  local dst="$TARGET/$rel"
  [ -f "$src" ] || { echo "warning: template missing: $rel" >&2; return; }
  mkdir -p "$(dirname "$dst")"
  if [ -f "$dst" ] && ! cmp -s "$src" "$dst"; then
    cp "$dst" "$dst.bak"
    echo "warning: preserved existing $rel as $rel.bak"
  fi
  cp "$src" "$dst"
  echo "updated: $rel"
}

copy_file .github/workflows/osv-scanner.yml
copy_file .github/workflows/semgrep.yml
copy_file .github/workflows/gitleaks.yml
copy_file .gitleaks.toml
copy_file .semgrepignore
copy_file .pre-commit-config.yaml
copy_file scripts/semgrep-diff.sh
copy_file scripts/security-scan.sh
chmod +x scripts/semgrep-diff.sh scripts/security-scan.sh 2>/dev/null || true

DEPENDABOT="$TARGET/.github/dependabot.yml"
if [ -e "$DEPENDABOT" ]; then
  echo "preserved: .github/dependabot.yml already exists; reconcile it manually"
else
  mkdir -p "$TARGET/.github"
  {
    echo "# Generated by XTRM security-bootstrap on $(date +%F). Review monorepo directories."
    echo "version: 2"
    echo "updates:"
    for eco in "${ECOSYSTEMS[@]}"; do
      label="$eco"
      [ "$eco" = pip ] && label=python
      [ "$eco" = npm ] && label=javascript
      cat <<EOF
  - package-ecosystem: $eco
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    labels: [dependencies, $label]
EOF
    done
  } > "$DEPENDABOT"
  echo "created: .github/dependabot.yml"
fi

# Preserve any existing pre-push implementation behind a managed wrapper. Both
# hooks receive the original refs on stdin. Do not silently replace local logic.
PREPUSH_SRC="$SOURCE/templates/.githooks/pre-push.template"
if [ -f "$PREPUSH_SRC" ]; then
  mkdir -p "$TARGET/.githooks"
  cp "$PREPUSH_SRC" "$TARGET/.githooks/.security-pipeline-baseline"
  chmod +x "$TARGET/.githooks/.security-pipeline-baseline"

  if [ -f "$TARGET/.githooks/pre-push" ] && ! grep -q 'security-pipeline-managed-wrapper' "$TARGET/.githooks/pre-push"; then
    if [ -e "$TARGET/.githooks/pre-push.local" ]; then
      mv "$TARGET/.githooks/pre-push.local" "$TARGET/.githooks/pre-push.local.bak.$(date +%s)"
    fi
    mv "$TARGET/.githooks/pre-push" "$TARGET/.githooks/pre-push.local"
    chmod +x "$TARGET/.githooks/pre-push.local"
  fi

  cat > "$TARGET/.githooks/pre-push" <<'EOF'
#!/usr/bin/env bash
# security-pipeline-managed-wrapper
set -uo pipefail
REFS="$(cat)"
HOOKS_DIR="$(dirname "$0")"
for hook in .security-pipeline-baseline pre-push.local; do
  if [ -x "$HOOKS_DIR/$hook" ]; then
    echo "$REFS" | "$HOOKS_DIR/$hook" "$@"
    rc=$?
    [ "$rc" -eq 0 ] || exit "$rc"
  fi
done
EOF
  chmod +x "$TARGET/.githooks/pre-push"
fi

# Show scope before mutation. The caller is expected to inspect this diff.
git status --short
git diff -- .github .gitleaks.toml .semgrepignore .pre-commit-config.yaml scripts .githooks || true

git add .github .gitleaks.toml .semgrepignore .pre-commit-config.yaml scripts .githooks 2>/dev/null || true
if git diff --cached --quiet; then
  echo "No security-bootstrap changes to commit."
  exit 0
fi

git commit -m "feat(security): bootstrap repository security baseline"
git push -u origin "$BRANCH"
PR_URL="$(gh pr create --base "$DEFAULT_BRANCH" --head "$BRANCH" --title 'feat(security): bootstrap repository security baseline' --body 'Generated by the XTRM security-bootstrap skill. Review repository-specific scanner placement, allowlists, branch/ruleset policy, and CI results before merge.')"
echo "PR: $PR_URL"

# Best-effort repository security toggles. Failure is explicit and does not
# invalidate the generated PR because token/repository permissions vary.
if gh api -X PATCH "/repos/$SLUG" \
  -f 'security_and_analysis[secret_scanning][status]=enabled' \
  -f 'security_and_analysis[secret_scanning_push_protection][status]=enabled' >/dev/null 2>&1; then
  echo "enabled: secret scanning + push protection"
else
  echo "warning: could not enable secret scanning/push protection; verify repository settings"
fi

if gh api -X PUT "/repos/$SLUG/vulnerability-alerts" >/dev/null 2>&1; then
  echo "enabled: Dependabot vulnerability alerts"
else
  echo "warning: could not enable Dependabot vulnerability alerts"
fi

echo "Next: inspect the PR, verify current ruleset/branch requirements, and observe CI."
